### ISSUE TITLE
Attribute spread

### ISSUE THREAD

**Issue by daig** [pzavolinsky/elmx#11]
The attribute spread example in the [live demo](http://pzavolinsky.github.io/elmx/) seems to be broken

```html
attrsGreeting : List (Attribute msg) -> Html msg
attrsGreeting attrs = <div {:attrs}>Hi</div>
```
goes to
```elm
attrsGreeting : List (Attribute msg) -> Html msg
attrsGreeting attrs = Html.div [(:attrs)] [Html.text "Hi"]
```

Handling attribute spread would be great for handling styling children natively in elm

**Comment by pzavolinsky** [comment]
Hi @daig , thanks for finding this bug

I've just pushed a new version that fixes this issue, check `elmx@1.0.7`, Atom's `language-elmx@1.2.8` or the updated the [live demo](http://pzavolinsky.github.io/elmx/).

Cheers!
