### ISSUE TITLE
Consider renaming repo to elm-jsx

### ISSUE THREAD

**Issue by rymohr** [pzavolinsky/elmx#3]
I like the .elmx extension but the name makes this project hard for people to find at the moment. I googled for "elm jsx" and it doesn't even show up.

I was surprised (and excited) to stumble on it at the bottom of https://github.com/elm-guides/elm-for-js/issues/5

**Comment by pzavolinsky** [comment]
Google has (finally) cached up with this so I'm closing the issue.

Thanks @rymohr  for reporting it.

Cheers!
