### ISSUE TITLE
Doesn't works with wepack

### ISSUE THREAD

**Issue by xgrommx** [pzavolinsky/elmx#4]

**Comment by domenkozar** [comment]
https://www.npmjs.com/package/elmx-webpack-preloader

**Comment by pzavolinsky** [comment]
Very cool, @domenkozar !

Updated the README to include a link to that package and published a new version with the updated README to [npm](https://www.npmjs.com/package/elmx#webpack-integration).

Cheers!

**Comment by domenkozar** [comment]
BTW, if you have any hints about Elm 0.17: https://github.com/vic/elmx-webpack-preloader/issues/1
