### ISSUE TITLE
wrong infix expression translation

### ISSUE THREAD

**Issue by vilinski** [pzavolinsky/elmx#8]
* Expression with two infix operators: 
```
<img src={"http://foo.com/bar" ++ authorId ++ ".png"}></img>
```

becomes

```
Html.img [Html.Attributes.attribute "src" ("http://foo.com/bar" ++ authorId ".png")] []
```

* The second thing should be evt. a separate issue. Note a space here before closing tag:

```
<ul class="message-list">{: List.map chatMessage model.messages } </ul>
```
it translates to

```
Html.ul [Html.Attributes.attribute "class" "message-list"] ( List.map chatMessage model.messages  ++ [ ])
```
Without the space it doesn't compile anymore

```
Html.ul [Html.Attributes.attribute "class" "message-list"]  List.map chatMessage model.messages 
```

reproducible in [TryElmx](http://pzavolinsky.github.io/elmx/)

**Comment by pzavolinsky** [comment]
Hi @vilinski thanks for reporting these bugs and for the regression examples. 

I just pushed version `1.0.6` that should fix both issues.

I also updated the  [language-elmx](https://atom.io/packages/language-elmx) Atom package and the [TryElmx](http://pzavolinsky.github.io/elmx/) interactive cheatsheet.

Cheers!

**Comment by vilinski** [comment]
Thanks for the fast fixes! However the ` ++ [ ]` quirk with space is still here. Or is any intention behind?
